from pathlib import Path

from .constants import EPNames
from .model_parameter import ModelParameter, RuntimeOverwrite


def create_model_parameter(aitk, name: str, configFile: Path):
    oliveFile = aitk.get("oliveFile")
    requirements = aitk.get("requirements", None)
    runtimeOverwrite = None
    if requirements:
        runtimeOverwrite = RuntimeOverwrite(autoGenerated=True, executeRequirement=requirements)
    aitkRuntimeOverwrite = aitk.get("runtimeOverwrite")
    if aitkRuntimeOverwrite:
        if runtimeOverwrite is None:
            runtimeOverwrite = RuntimeOverwrite(autoGenerated=True)
        executeEp = aitkRuntimeOverwrite.get("executeEp")
        runtimeOverwrite.executeEp = EPNames(executeEp)

    requirements_patches = aitk.get("requirementsPatches")
    evalRuntime = aitk.get("evalRuntime")

    parameter = ModelParameter(
        name=name,
        oliveFile=oliveFile,
        runtimeOverwrite=runtimeOverwrite,
        executeRuntimeFeatures=requirements_patches,
        evalRuntime=evalRuntime,
    )
    parameter._file = str(configFile) + ".config"
    return parameter
