import json
from pathlib import Path
from typing import Optional

from .constants import OlivePassNames, OlivePropertyNames, PhaseTypeEnum
from .generator_common import create_model_parameter
from .model_info import ModelList
from .model_parameter import Section
from .parameters import Parameter
from .utils import isLLM_by_id, open_ex


def generate_quantization_config(configFile: Path, modelList: ModelList) -> Optional[Section]:
    """
    Generates a quantization configuration section for the given file.
    """
    with open_ex(configFile, "r") as f:
        content = json.load(f)
    parameters = []
    data_configs = content.get(OlivePropertyNames.DataConfigs, [])
    for k, v in content[OlivePropertyNames.Passes].items():
        if v[OlivePropertyNames.Type].lower() == OlivePassNames.OnnxStaticQuantization:
            activation_type = v.get(OlivePropertyNames.ActivationType)
            if activation_type:
                parameters.append(
                    Parameter(
                        autoGenerated=True,
                        template=Parameter(
                            template="ActivationType",
                            path=f"{OlivePropertyNames.Passes}.{k}.{OlivePropertyNames.ActivationType}",
                        ),
                    )
                )
            precision = v.get(OlivePropertyNames.Precision)
            if precision:
                parameters.append(
                    Parameter(
                        autoGenerated=True,
                        template=Parameter(
                            template="WeightType",
                            path=f"{OlivePropertyNames.Passes}.{k}.{OlivePropertyNames.Precision}",
                        ),
                    )
                )
            data_config = v.get(OlivePropertyNames.DataConfig)
            if data_config:
                for i in range(len(data_configs)):
                    if data_configs[i].get(OlivePropertyNames.Name) == data_config:
                        load_dataset_config = data_configs[i].get(OlivePropertyNames.LoadDatasetConfig)
                        data_name = load_dataset_config.get(OlivePropertyNames.DataName)
                        parameters.append(
                            Parameter(
                                autoGenerated=True,
                                template=Parameter(
                                    template="QuantizationDataset",
                                    path=f"{OlivePropertyNames.DataConfigs}[{i}].{OlivePropertyNames.LoadDatasetConfig}.{OlivePropertyNames.DataName}",
                                    values=[data_name],
                                ),
                            )
                        )

                        subset = load_dataset_config.get(OlivePropertyNames.Subset)
                        if subset:
                            subsets = modelList.DatasetSubset.get(data_name)
                            if not subsets:
                                subsets = [subset]
                            parameters.append(
                                Parameter(
                                    autoGenerated=True,
                                    template=Parameter(
                                        template="QuantizationDatasetSubset",
                                        path=f"{OlivePropertyNames.DataConfigs}[{i}].{OlivePropertyNames.LoadDatasetConfig}.{OlivePropertyNames.Subset}",
                                        values=subsets,
                                    ),
                                )
                            )

                        split = load_dataset_config.get(OlivePropertyNames.Split)
                        if split:
                            # use template default or DatasetSplit
                            splits = modelList.DatasetSplit.get(data_name)
                            parameters.append(
                                Parameter(
                                    autoGenerated=True,
                                    template=Parameter(
                                        template="QuantizationDatasetSplit",
                                        path=f"{OlivePropertyNames.DataConfigs}[{i}].{OlivePropertyNames.LoadDatasetConfig}.{OlivePropertyNames.Split}",
                                        values=splits,
                                    ),
                                )
                            )

                        pre_process_data_config = data_configs[i].get(OlivePropertyNames.PreProcessDataConfig)
                        max_samples = pre_process_data_config.get(OlivePropertyNames.MaxSamples)
                        if max_samples:
                            parameters.append(
                                Parameter(
                                    autoGenerated=True,
                                    template=Parameter(
                                        template="QuantizationDatasetSize",
                                        path=f"{OlivePropertyNames.DataConfigs}[{i}].{OlivePropertyNames.PreProcessDataConfig}.{OlivePropertyNames.MaxSamples}",
                                    ),
                                )
                            )
                        break

    if parameters:
        return Section(
            autoGenerated=True,
            name="Quantize",
            phase=PhaseTypeEnum.Quantization,
            parameters=parameters,
        )
    return None


def generate_amd_quantization_config(configFile: Path, modelList: ModelList) -> Optional[Section]:
    with open_ex(configFile, "r") as f:
        content = json.load(f)
    parameters = []
    for k, v in content[OlivePropertyNames.Passes].items():
        if v[OlivePropertyNames.Type].lower() == OlivePassNames.QuarkQuantization:
            data_name = v.get(OlivePropertyNames.Dataset)
            if data_name:
                parameters.append(
                    Parameter(
                        autoGenerated=True,
                        template=Parameter(
                            template="QuantizationDataset",
                            path=f"{OlivePropertyNames.Passes}.{k}.{OlivePropertyNames.Dataset}",
                            values=[data_name],
                        ),
                    )
                )
            max_samples = v.get(OlivePropertyNames.NumCalibData)
            if max_samples:
                parameters.append(
                    Parameter(
                        autoGenerated=True,
                        template=Parameter(
                            template="QuantizationDatasetSize",
                            path=f"{OlivePropertyNames.Passes}.{k}.{OlivePropertyNames.NumCalibData}",
                        ),
                    )
                )
            break

    if parameters:
        return Section(
            autoGenerated=True,
            name="Quantize",
            phase=PhaseTypeEnum.Quantization,
            parameters=parameters,
        )
    return None


def generator_amd(id: str, recipe, folder: Path, modelList: ModelList):
    aitk = recipe.get("aitk", {})
    auto = aitk.get("auto", True)
    isLLM = isLLM_by_id(id)
    if not auto or not isLLM:
        return
    amd_runtime_values: list[str] = recipe.get("devices", [recipe.get("device")])
    name = f"Convert to AMD {"/".join([runtime.upper() for runtime in amd_runtime_values])}"

    file = recipe.get("file")
    configFile = folder / file

    parameter = create_model_parameter(aitk, name, configFile)
    parameter.addCpu = False
    parameter.isLLM = isLLM

    quantize = generate_amd_quantization_config(configFile, modelList)
    if not quantize:
        quantize = generate_quantization_config(configFile, modelList)
    if quantize:
        parameter.sections.append(quantize)

    parameter.writeIfChanged()
    print(f"\tGenerated AMD configuration for {file}")
